#!/bin/bash

# Created 06/17/2021
# Script to fuzz HTTP requests by checking all HTTP verbs and outputting the response codes.

# Help
while getopts ":dh" option; do
	case "$option" in

		d)
			echo "Including the DELETE request type"
			del_function(){
				curl -s -I -X DELETE $URL | grep 'HTTP' | sed 's\^\DELETE \'
			}
			;;

		h)
			echo "Usage: ./fuzzyhttp"
			echo
			echo "-a   Include all request types. This includes DELETE"
			echo "Example: ./fuzzyhttp -a"
			echo
			echo "-d   Include a DELETE request"
			echo "Example : ./fuzzyhttp -d"
			echo
			echo "-h   Help menu"
			;;

		?)
			echo "Usage: ./fuzzyhttp"
			echo "For help, use -h"
			exit 1
			;;
	esac
done

echo Enter in a URL to fuzz:
read URL

echo 
echo HTTP requests to $URL
echo 

# Output results:
curl -s -I $URL | grep 'HTTP' | sed 's\^\GET \'
curl -s -I -X HEAD $URL | grep 'HTTP' | sed 's\^\HEAD \'
curl -s -I -X POST $URL | grep  'HTTP' | sed 's\^\POST \'
curl -s -I -X PUT $URL | grep 'HTTP' | sed 's\^\PUT \'
curl -s -I -X CONNECT $URL | grep 'HTTP' | sed 's\^\CONNECT  \'
curl -s -I -X OPTIONS $URL | grep 'HTTP' | sed 's\^\OPTIONS  \'
curl -s -I -X TRACE $URL | grep 'HTTP' | sed 's\^\TRACE \'
curl -s -I -X PATCH $URL | grep 'HTTP' | sed 's\^\PATCH \'
type del_function &>/dev/null && del_function
