#!/bin/bash

# Created 06/17/2021
# Script to fuzz HTTP requests by checking all HTTP verbs and outputting the response codes.

# Help
while getopts ":h" option; do
	echo Usage: ./fuzzyhttp
	echo 
	echo -d   Include a DELETE request - THIS IS CURRENTLY BROKEN
	echo Example: ./fuzzyhttp -d
	exit
done

echo Enter in a URL to fuzz:
read URL

#while getopts ":d" option; do
#	curl -X DELETE $URL
#done

echo 
echo HTTP requests to $URL
echo 


curl -s -I $URL | grep 'HTTP' | sed 's\^\GET \'
curl -s -I -X HEAD $URL | grep 'HTTP' | sed 's\^\HEAD \'
curl -s -I -X POST $URL | grep  'HTTP' | sed 's\^\POST \'
curl -s -I -X PUT $URL | grep 'HTTP' | sed 's\^\PUT \'
curl -s -I -X CONNECT $URL | grep 'HTTP' | sed 's\^\CONNECT  \'
curl -s -I -X OPTIONS $URL | grep 'HTTP' | sed 's\^\OPTIONS  \'
curl -s -I -X TRACE $URL | grep 'HTTP' | sed 's\^\TRACE \'
curl -s -I -X PATCH $URL | grep 'HTTP' | sed 's\^\PATCH \'

